### ISSUE TITLE
Why each april tag has a two-square size boundary?

### ISSUE THREAD

**Issue by fcc315** [wangdongustc/AprilTagGenerator#2]
Hello, 

Thanks for your repo first! I am testing an Apriltag detector: https://github.com/swatbotics/apriltag

It fails to detect the board generated by your code.
I am checking the detector's parameters, and I noticed that your Apriltag has a two-square size black boundary. I am wondering whether this causes the failure of detection.

May I know why it has a two-square size black boundary? Does it matter on detection or calibration results?

**Comment by wangdongustc** [comment]
Hi @fcc315 ,

Thanks for your interest!

> It fails to detect the board generated by your code.
> I am checking the detector's parameters, and I noticed that your Apriltag has a two-square size black boundary. I am wondering whether this causes the failure of detection.

Yes. The boundary size should have caused the detection failure. To be noticed, there is a "border" parameter in the UI to let you change this.

Besides, if you use the apriltags detector from the mentioned repo in the README.md, you will find that there is a commit that adds the `blackBorder` as one of the detection parameters: https://github.com/huangqinjin/apriltags/commit/9e73d0ed1c53cd64170a48e63ed2a8961514fc6c.

> May I know why it has a two-square size black boundary? Does it matter on detection or calibration results?

This is actually by design.

We first noticed the black border thing when we were trying to calibrate cameras with the [ethz-asl/kalibr](https://github.com/ethz-asl/kalibr) program. By default it uses the same kind of apriltags that have two square size black border. You can find their examples on their wiki: [ethz-asl/kalibr/wiki/calibration-targets](https://github.com/ethz-asl/kalibr/wiki/calibration-targets).

Later when we were designing our own camera calibration program, we noticed that a larger black border usually helps the sub-pixel corner detection of the four corners of a tag. Although usually the apriltag detector provides a sub-pixel result, we can usually have a more precise result based on it with something like the [cv::cornerSubPix](https://docs.opencv.org/3.4/dd/d1a/group__imgproc__feature.html#ga354e0d7c86d0d9da75de9b9701a9a87e) from OpenCV. A larger border helps to create a stable image area like the first one in the following picture in most cases. You can choose a larger area to do sub-pixel calculation without worrying about the noise from the white squares inside the tag.

![image](https://user-images.githubusercontent.com/3369452/175571541-ef549f21-4eaf-4e19-965c-183cd909daac.png) (picture from the opencv doc above).

**Comment by fcc315** [comment]
Hi @wangdongustc,

Thank you so much for your detailed reply! My problem is now solved and your explanations enhance my understanding!
